name: cw_starknet
description: Starknet support for Cake Wallet
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cw_core:
    path: ../cw_core
  starknet:
    git:
      url: https://github.com/focustree/starknet.dart.git
      path: packages/starknet
  flutter:
    sdk: flutter
  hive: ^2.2.3
  mobx: ^2.3.0+1
  bip39: ^1.0.6
  bip32: ^2.0.0
  crypto: ^3.0.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.15
  mobx_codegen: ^2.1.1
